export const technologies = [
  'HTML',
  'CSS',
  'JS',
  'React',
  'Git',
  'Express.js',
  'mongoDB',
];

export const portfolioInfo = [
  {
    title: 'Статичный сайт',
    url: '#',
  },
  {
    title: 'Адаптивный сайт',
    url: '#',
  },
  {
    title: 'Одностраничное приложение',
    url: '#',
  },
];

export const movies = [
  {
    id: 1,
    nameRU: 'Киноальманах «100 лет дизайна»',
    duration: 107,
    trailer: 'https://youtu.be/dQw4w9WgXcQ?si=NsbEVxlOPe3Zqb9i',
    image: 'https://picsum.photos/360/201',
    saved: false,
  },
  {
    id: 2,
    nameRU: 'В погоне за Бенкси',
    duration: 107,
    trailer: 'https://youtu.be/dQw4w9WgXcQ?si=NsbEVxlOPe3Zqb9i',
    image: 'https://picsum.photos/360/201',
    saved: true,
  },
  {
    id: 3,
    nameRU: 'Баския: Взрыв реальности',
    duration: 107,
    trailer: 'https://youtu.be/dQw4w9WgXcQ?si=NsbEVxlOPe3Zqb9i',
    image: 'https://picsum.photos/360/201',
    saved: true,
  },
  {
    id: 4,
    nameRU: 'Бег это свобода',
    duration: 107,
    trailer: 'https://youtu.be/dQw4w9WgXcQ?si=NsbEVxlOPe3Zqb9i',
    image: 'https://picsum.photos/360/201',
    saved: true,
  },
  {
    id: 5,
    nameRU: 'Книготорговцы',
    duration: 107,
    trailer: 'https://youtu.be/dQw4w9WgXcQ?si=NsbEVxlOPe3Zqb9i',
    image: 'https://picsum.photos/360/201',
    saved: true,
  },
  {
    id: 6,
    nameRU: 'Когда я думаю о Германии ночью',
    duration: 107,
    trailer: 'https://youtu.be/dQw4w9WgXcQ?si=NsbEVxlOPe3Zqb9i',
    image: 'https://picsum.photos/360/201',
    saved: true,
  },
  {
    id: 7,
    nameRU: 'Gimme Danger: История Игги и The Stooges',
    duration: 107,
    trailer: 'https://youtu.be/dQw4w9WgXcQ?si=NsbEVxlOPe3Zqb9i',
    image: 'https://picsum.photos/360/201',
    saved: true,
  },
  {
    id: 8,
    nameRU: 'Дженис: Маленькая девочка грустит',
    duration: 107,
    trailer: 'https://youtu.be/dQw4w9WgXcQ?si=NsbEVxlOPe3Zqb9i',
    image: 'https://picsum.photos/360/201',
    saved: true,
  },
  {
    id: 9,
    nameRU: 'Соберись перед прыжком',
    duration: 107,
    trailer: 'https://youtu.be/dQw4w9WgXcQ?si=NsbEVxlOPe3Zqb9i',
    image: 'https://picsum.photos/360/201',
    saved: false,
  },
  {
    id: 10,
    nameRU: 'Пи Джей Харви: A dog called money',
    duration: 107,
    trailer: 'https://youtu.be/dQw4w9WgXcQ?si=NsbEVxlOPe3Zqb9i',
    image: 'https://picsum.photos/360/201',
    saved: false,
  },
  {
    id: 11,
    nameRU: 'По волнам: Искусство звука в кино',
    duration: 107,
    trailer: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    image: 'https://picsum.photos/360/201',
    saved: false,
  },
];
